# Generated by Django 4.2.16 on 2024-09-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amountpaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentstatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
