# Generated by Django 4.2.16 on 2024-09-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_address1_order_address_remove_order_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address1',
        ),
    ]
