# Generated by Django 4.2.16 on 2024-09-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_address_order_address1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
