# Generated by Django 4.2.16 on 2024-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_delete_orders_delete_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
